### PR TITLE
Delete singleservernocontainers installation doc

### PR DESCRIPTION
**Pull request by julianladisch**
The single server no containers installation document
is outdated, it's from November 2020.

It requires the Debian repository http://folio-repo.bib-bvb.de
this has been offline for a long time.

The Debian containers doesn't allow two tenants running
two different versions of the same module.

Therefore this installation document should be removed.

It is not lost because it remains in the git history:
https://github.com/folio-org/docs/commits/master

### CODE REVIEW

**Comment by inkuss** [comment]
It is clear that this document should not be included in the Lotus, Kiwi, Juniper and Iris branches (and as a matter of fact, it is not in there).
But this is a pull request for the master branch. What is the meaning of the master branch, anyway ?  Isn't this branch unused ??

**Comment by julianladisch** [comment]
https://dev.folio.org/guidelines/contributing/#git-and-branches

> For all FOLIO code repositories, we are trying to follow [GitHub Flow](https://guides.github.com/introduction/flow/).
> In short, the master branch is always the head of latest development. Anything merged into master should be of such good quality that at any time a snapshot from master passes all tests, and can be deployed. That is not to say that it will be free of bugs; we are not superhuman.
> All work is done in feature branches, and merged to master via pull requests.

> Create a long-lived branch for that major/feature version

For documentation each flower release (Lotus, Kiwi, ...) is a major version.

After this pull request has been accepted I will create back-port pull requests ([cherry-pick](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/cherry-picking-a-commit)) for the flower release branches.

**Comment by inkuss** [comment]
We are currently developing in the Lotus branch. If the master branch should be the head of latest development, according to the GitHub Flow guidelines, the contents of the Lotus branch should be pushed to the master branch.

**Comment by julianladisch** [comment]
If the master branch is not used it should be deleted after the lotus branch has been [set as default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch).

**Comment by sekjal** [comment]
At this time, master powers docs.folio.org, and each flower release (i.e.
kiwi.docs.folio.org) is powered off the corresponding branch.

**Comment by inkuss** [comment]
The contents of docs.folio.org don't really make sense. Concerning the installation section, they contain a copy of the Iris install documentation and the "single server no containers" prescription. This is in a non-maintained state.
Also, if I point my browser tp https://docs.folio.org/ and then click on "go to the docs", I reach kiwi.doc.folio.org, which makes sense. But https://kiwi.docs.folio.org/docs/ is not really in use, unless one explicitely enters this URL in the browser line (why should one do this ?).

I suggest that the master branch should either be deleted, contain a copy of the latest released version (Kiwi) or be used as the development branch (Lotus). In the latter case, the lotus branch should be deleted.

**Comment by sekjal** [comment]
Closing, since we're going to do master/main cleanup so that our primary branch better reflects the current state rather than a snapshot from Honeysuckle days

**Pull request closed without merging**
