### PR TITLE
System software versions: Explain lists and flower releases

### PR DESCRIPTION
**Pull request by julianladisch**

### CODE REVIEW

**Comment by dltj** [comment]
Do we need to formalize a way of keeping this list updated?  I'm not aware of a release manager's checklist anywhere, but if there is one then adding a line to update this document makes sense.

**Comment by dltj** [comment]
I've asked on the Product Owners slack channel is there is something like a release manager's checklist so we can have some mechanized way of ensuring this page is updated with each new release.

**Comment by julianladisch** [comment]
Until then, I will take care of this table.

**Review by dltj — APPROVED** [review]
Okay, many thanks, @julianladisch.

**Pull request merged**
