### PR TITLE
Nolana

### PR DESCRIPTION
**Pull request by inkuss**
This is my Christmas present to the FOLIO Community: A **tested** single-server fresh installation documentation for Nolana.

### CODE REVIEW

**Comment by inkuss** [comment]
Ah, these has merge conflicts, but they are (almost) all in the files which I did not touch. Must be that origin/nolana had been changed in the meantime, massively. I have been only working on this for less than one week, since last Wednesday. I only changed singleserverfreshinstall.md. Will it be my task to resolve conflicts other than in singleservefreshinstall.md, to get this PR merged ?

**Comment by inkuss** [comment]
Why does git hub show me a "merge conflict" like this:
`<<<<<<< HEAD
* In the same file, change **log_timezone** and **timezone**, otherwise they will be UTC.
=======
>>>>>>> 67ee15336fbba885575de693ae6be7f3d41720ac
`
It is obvious that I want to insert the line. How can I stop git hub from doing this ?

**Comment by enettifee** [comment]
@inkuss can you sync your working branch first (which should pick up the Nolana updates, I think) and then try the merge?

**Comment by inkuss** [comment]
@enettifee , I did that, but I am getting the same conflicts (which I would then have to resolve locally)
`git remote -v
inkuss  https://github.com/inkuss/docs.git (fetch)
inkuss  https://github.com/inkuss/docs.git (push)
origin  https://github.com/folio-org/docs.git (fetch)
origin  https://github.com/folio-org/docs.git (push)

kuss@hbz-187-11 MINGW64 ~/folio/docs (nolana)
$ git pull origin nolana
From https://github.com/folio-org/docs
 * branch            nolana     -> FETCH_HEAD
Auto-merging content/en/docs/_index.md
CONFLICT (content): Merge conflict in content/en/docs/_index.md
Auto-merging content/en/docs/Settings/System_software_versions/System_software_versions.md
CONFLICT (content): Merge conflict in content/en/docs/Settings/System_software_versions/System_software_versions.md
Auto-merging content/en/docs/Settings/Settings_circulation/settings_circulation.md
CONFLICT (content): Merge conflict in content/en/docs/Settings/Settings_circulation/settings_circulation.md
CONFLICT (add/add): Merge conflict in content/en/docs/Platform essentials/Permissions/_index.md
Auto-merging content/en/docs/Platform essentials/Permissions/_index.md
Auto-merging content/en/docs/Platform essentials/Item status/itemstatus.md
CONFLICT (content): Merge conflict in content/en/docs/Platform essentials/Item status/itemstatus.md
Auto-merging content/en/docs/Metadata/Inventory/MARCAuthority.md
CONFLICT (add/add): Merge conflict in content/en/docs/Getting started/Installation/singleserverfreshinstall.md
Auto-merging content/en/docs/Getting started/Installation/singleserverfreshinstall.md
Auto-merging content/en/docs/ERM/Licenses/_index.md
CONFLICT (content): Merge conflict in content/en/docs/ERM/Licenses/_index.md
Auto-merging content/en/docs/ERM/Agreements/_index.md
CONFLICT (content): Merge conflict in content/en/docs/ERM/Agreements/_index.md
CONFLICT (add/add): Merge conflict in content/en/docs/Bulk Edit/_index.md
Auto-merging content/en/docs/Bulk Edit/_index.md
Auto-merging content/en/docs/Acquisitions/Orders/_index.md
CONFLICT (content): Merge conflict in content/en/docs/Acquisitions/Orders/_index.md
Auto-merging content/en/docs/Access/Circulation log/circ_log.md
CONFLICT (content): Merge conflict in content/en/docs/Access/Circulation log/circ_log.md
Automatic merge failed; fix conflicts and then commit the result.`

**Comment by inkuss** [comment]
Let me try something else, since I have only changed one file...

**Comment by inkuss** [comment]
Created a new Pull Request, Closing this one.

**Pull request closed without merging**
